// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        int32            `json:"id"`
	PostID    int32            `json:"post_id"`
	UserID    int32            `json:"user_id"`
	Content   string           `json:"content"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Post struct {
	ID        int32   `json:"id"`
	UserID    int32   `json:"user_id"`
	Title     string  `json:"title"`
	Content   *string `json:"content"`
	Published *bool   `json:"published"`
}

type User struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Status    *string          `json:"status"`
	LastLogin pgtype.Timestamp `json:"last_login"`
}
