// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) error
	// PostgreSQL queries with $1, $2 placeholders
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteComment(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetPostComments(ctx context.Context, postID int32) ([]Comment, error)
	GetRecentUsers(ctx context.Context) ([]User, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserComments(ctx context.Context, userID int32) ([]Comment, error)
	GetUserPosts(ctx context.Context, id int32) ([]Post, error)
	GetUserWithPosts(ctx context.Context, id int32) ([]GetUserWithPostsRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
}

var _ Querier = (*Queries)(nil)
