// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :exec
INSERT INTO comments (post_id, user_id, content) 
VALUES ($1, $2, $3)
`

type CreateCommentParams struct {
	PostID  int32  `json:"post_id"`
	UserID  int32  `json:"user_id"`
	Content string `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.Exec(ctx, createComment, arg.PostID, arg.UserID, arg.Content)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (name, email) VALUES ($1, $2)
`

type CreateUserParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Name, arg.Email)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getPostComments = `-- name: GetPostComments :many
SELECT id, post_id, user_id, content, created_at FROM comments 
WHERE post_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) GetPostComments(ctx context.Context, postID int32) ([]Comment, error) {
	rows, err := q.db.Query(ctx, getPostComments, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentUsers = `-- name: GetRecentUsers :many
SELECT id, name, email, created_at, status, last_login FROM users 
WHERE created_at > NOW() - INTERVAL '7 days'
ORDER BY created_at DESC
`

func (q *Queries) GetRecentUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getRecentUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Status,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, created_at, status, last_login FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.Status,
		&i.LastLogin,
	)
	return i, err
}

const getUserComments = `-- name: GetUserComments :many
SELECT id, post_id, user_id, content, created_at FROM comments 
WHERE user_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) GetUserComments(ctx context.Context, userID int32) ([]Comment, error) {
	rows, err := q.db.Query(ctx, getUserComments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPosts = `-- name: GetUserPosts :many
SELECT posts.id, posts.user_id, posts.title, posts.content, posts.published FROM posts
JOIN users ON posts.user_id = users.id
WHERE users.id = $1
`

func (q *Queries) GetUserPosts(ctx context.Context, id int32) ([]Post, error) {
	rows, err := q.db.Query(ctx, getUserPosts, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Published,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithPosts = `-- name: GetUserWithPosts :many
SELECT u.id, u.name, u.email, u.created_at, u.status, u.last_login, p.id, p.user_id, p.title, p.content, p.published FROM users u
LEFT JOIN posts p ON u.id = p.user_id
WHERE u.id = $1
`

type GetUserWithPostsRow struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Status    *string          `json:"status"`
	LastLogin pgtype.Timestamp `json:"last_login"`
	ID_2      *int32           `json:"id_2"`
	UserID    *int32           `json:"user_id"`
	Title     *string          `json:"title"`
	Content   *string          `json:"content"`
	Published *bool            `json:"published"`
}

func (q *Queries) GetUserWithPosts(ctx context.Context, id int32) ([]GetUserWithPostsRow, error) {
	rows, err := q.db.Query(ctx, getUserWithPosts, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserWithPostsRow
	for rows.Next() {
		var i GetUserWithPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Status,
			&i.LastLogin,
			&i.ID_2,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.Published,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, created_at, status, last_login FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Status,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users SET email = $1 WHERE id = $2
`

type UpdateUserEmailParams struct {
	Email string `json:"email"`
	ID    int32  `json:"id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.Email, arg.ID)
	return err
}
