name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v7
      
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Build binary
        run: |
          go mod download
          go build -ldflags="-s -w" -o app main.go
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app
            migrations/
            sqlc.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
